config/routes.rb
Prelims::Application.routes.draw do
  get 'password_resets/new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'questions#index'
  resources :questions do
    resources :sittings
    resources :question_ratings
    collection { post :search, to: 'questions#index' }

    resources :answers do
      resources :answer_ratings
    end
  end
  resources :password_resets
  resources :questiontags
  resources :finished_questions
  resources :answers do
    resources :answer_ratings
  end
  resources :users
  resources :tags
  resources :user_sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'user_sessions#new',         via: 'get'
  match '/signout', to: 'user_sessions#destroy',     via: 'delete'
  match '/help' => 'static#help', via: 'get'
  match '/summary' => 'static#summary', via: 'get'
  match '/teacher' => 'static#teacher', via: 'get'
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id               :integer          not null, primary key
#  subject_id       :integer
#  source_id        :integer
#  professor_id     :integer
#  mini             :integer
#  created_at       :datetime
#  updated_at       :datetime
#  pdf_file_name    :string(255)
#  pdf_content_type :string(255)
#  pdf_file_size    :integer
#  pdf_updated_at   :datetime
#  answers_count    :integer          default(0)
#  overall          :float            default(3.0)
#  difficulty       :float            default(3.0)
#  uniqueness       :float            default(3.0)
#

## Association to the Question Table
class Question < ActiveRecord::Base
  belongs_to :subject
  belongs_to :source
  belongs_to :professor
  validates :source, :subject, presence: true
  has_many :sittings, dependent: :destroy
  has_many :question_ratings, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :finished_questions, dependent: :destroy
  has_many :tags, through: :questiontags
  has_many :terms, through: :sittings
  has_many :questiontags, dependent: :destroy
  accepts_nested_attributes_for :sittings
  has_attached_file :pdf
  after_create :update_question_ratings

  def update_question_ratings
    @ratings = QuestionRating.where(question_id: id)
    self.overall = @ratings.average(:overall)
    self.difficulty = @ratings.average(:difficulty)
    self.uniqueness = @ratings.average(:uniqueness)
    self.save!
  end

  def total_answers
    answers.size
  end

  def subj
    subject.name
  end

  def prof
    professor.name
  end

  def last_date
    @sittings = sittings.sort_by { |u| u.year }
    @sitting = @sittings.last
    @sitting.sort_sitting
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :find_question, only: [:show, :destroy, :edit, :update]

  def find_question
    @question = Question.find(params[:id])
  end

  def index
    @search = Question.includes(:sittings, :subject, :tags, :source, :professor, :terms).search(params[:q])
    @questions = @search.result.page(params[:page]).per(25)
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    @current_user = current_user
  end

  def create
    @question = Question.new(question_params)
    @sitting = @question.sittings.build(params[:sitting].permit(:term_id, :year, :number))
    params[:tags][:id].each do |tag|
      if !tag.empty?
	      @question.questiontags.build(:tag_id => tag)
      end
    end
    if @question.save
      redirect_to questions_path
    end
  end

  def new
    @question = Question.new
    @all_tags = Tag.all.order(:tag)
    @questiontag = @question.questiontags.build
    @question_sitting = @question.sittings.build
  end

  def show
    @questiontag = Questiontag.new
    if current_user.finished_questions.where("question_id = ?", params[:id]).size > 0
      @finished_question = current_user.finished_questions.where("question_id = ?", params[:id]).first
    else
      @finished_question = FinishedQuestion.new
    end

    if current_user.question_ratings.where("question_id = ?", params[:id]).size > 0
      @question_rating = current_user.question_ratings.where("question_id = ?", params[:id]).first
    else
      @question_rating = QuestionRating.new
    end

  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def edit
  end

  def update
    if @question.update_attributes(question_params)
      flash[:success] = "Question updated"
      redirect_to :root
    else
      render 'edit'
    end
  end
end


private
  def question_params
    params.require(:question).permit(:subject_id, :source_id, :professor_id,:mini,:pdf)
    #params.require(:question).permit!
  end

  def sort_column
    #Question.column_names.include?(params[:sort]) ? params[:sort] : "subject_id"
                        params[:sort] || "subject_id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

app/views/questions/_condition_fields.html.haml
= f.attribute_fields do |a|
  = a.attribute_select associations: [:sittings, :tags]
= f.predicate_select
= f.value_fields do |v|
  = v.text_field :value
= link_to "remove", '#', class: "remove_fields"

app/views/questions/_form.html.haml
= form_for :question, url: edit_question_path(params[:id]), :html => { :multipart => true } do |f|
  = f.label :subject
  = f.collection_select :subject_id, Subject.all, :id, :name, include_blank: true
  %p
  = f.label :source
  = f.collection_select :source_id, Source.all, :id, :source, include_blank: true
  %p
  = f.label :professor
  = f.collection_select  :professor_id, Professor.all, :id, :name, include_blank: true
  %p
  = f.label :mini
  = f.number_field  :mini
  %p
  = f.label  :file
  = f.file_field  :pdf
  %p
  = f.submit

app/views/questions/edit.html.haml
%h1 Edit Question

= form_for @question,  :url => {action: :update}, :html => { :multipart => true } do |f|
  = f.label :subject
  = f.collection_select :subject_id, Subject.all, :id, :name, include_blank: true
  %p
  = f.label :source
  = f.collection_select :source_id, Source.all, :id, :source, include_blank: true
  %p
  = f.label :professor
  = f.collection_select  :professor_id, Professor.all, :id, :name, include_blank: true
  %p
  = f.label :mini
  = f.number_field  :mini
  %p
  = f.label  :file
  = f.file_field  :pdf
  %p
  = f.submit

app/views/questions/index.html.haml
.center-block
  %h1 All Questions

  = search_form_for( @search, url: search_questions_path, method: :post) do |f|
    = f.condition_fields do |c|
      = render 'condition_fields', f: c
    %p= link_to_add_fields "Add Conditions", f, :condition
    .field
      Sort:
      = f.sort_fields do |s|
        = s.sort_select associations: [:sittings, :tags]
    = f.submit "Search"
  = paginate @questions, :method => :post
  %table.table.table-condensed.table-responsive#questions
    %thead
      %tr
        %th Subject
        %th Source
        %th Professor
        %th Mini
        %th
          %span{title: "Dates Asked"} Date
        %th
          %span{title: "Average Overall Rating"} Over
        %th
          %span{title: "Average Difficulty Rating"} Diff
        %th
          %span{title: "Average Uniqueness Rating"} Uniq
        %th
          %span{title: "Number of Answers Uploaded"} # Answers
        %th
          %span{title: "Finished?"} Fin?
        %th Tags
        %th PDF
        %th More
    %tbody
      - @questions.each do |question|
        %tr
          %td= question.subject.name
          %td= question.source.source
          %td= question.professor.name
          %td= question.mini
          %td
            - question.sittings.each do | sitting |
              = sitting.sort_sitting
              %br
          %td= question.overall
          %td= question.difficulty
          %td= question.uniqueness
          %td= question.total_answers
          - if question.finished_questions.where(user_id: current_user.id).size != 0
            %td Y
          - else
            %td
          %td
            - question.tags.each do |tag|
              = tag.tag
              %br
          %td
            = link_to("Down",question.pdf.url)
          %td= link_to "More", question_path(question)

  = link_to "Add new question", new_question_path

app/views/questions/new.html.haml
.hero-unit
  %h1 Create New Question

  = form_for :question, url: questions_path, :html => { :multipart => true } do |f|
    = f.label :subject
    = f.collection_select :subject_id, Subject.all, :id, :name, include_blank: true
    %p
    = f.label :source
    = f.collection_select :source_id, Source.all, :id, :source, include_blank: true
    %p
    = f.label :professor
    = f.collection_select  :professor_id, Professor.all, :id, :name, include_blank: true
    %p
    = fields_for(@questiontag) do |ab|
      = ab.label :tag, "Tags: hold crtl while clicking to select multiple"
      = collection_select :tags, :id, @all_tags, :id, :tag,  {}, {:multiple => true}
    %p
    = f.label :mini
    = f.number_field  :mini
    %p
    = fields_for(@question_sitting) do |e|

      = e.label :year
      = e.select :year, (1990...2014)

      = e.label  :term
      = e.collection_select :term_id, Term.all, :id, :term, include_blank: true

      = e.label  :number
      = e.text_field  :number

    = f.label  :file
    = f.file_field  :pdf

    %p
    = submit_tag 'Save Changes'

app/views/questions/show.html.haml
.container-fluid.row-fluid
  .span4
    = render 'finished_questions/form'
    = link_to 'Edit Question', edit_question_path(@question)
    %p
    = link_to("Download PDF",@question.pdf.url)
  .span4
    %h5
      Subject -
      = @question.subject.name
    %h5
      Professor -
      = @question.professor.name
    %h5
      Mini -
      = @question.mini
    %h5 Dates Asked
    - @question.sittings.each do | sitting |
      = sitting.print_sitting
      ,
    = link_to 'Add Date', new_question_sitting_path(@question)
  .span4
    %h5 Tags
    - @question.tags.each do | tag |
      = tag.tag
      ,
    = render 'questiontags/form'

.container-fluid.row-fluid.span12
  %h3.text-center Question Ratings
= render 'question_ratings/table'
.container-fluid.row-fluid.span12
  = render 'question_ratings/form'

.container-fluid.row-fluid.span12
  %h3.text-center Answers

%table.table.table-bordered
  %thead
    %tr
      %th Overall
      %th Clarity
      %th Detail
      %th Correctness
      %th Answer PDF
      %th User Name
      %th Typed?
      %th Review Answer
      %th
  %tbody
    - @question.answers.each do |answer|
      %tr
        %td= answer.overall
        %td= answer.clarity
        %td= answer.detail
        %td= answer.correctness
        %td= link_to("Download",answer.pdf.url)
        %td= answer.user.name
        - if answer.typed
          %td Y
        - else
          %td N
        %td= link_to 'More info', question_answer_path(:id => answer.id, :question_id => answer.question.id)
        - if answer.user.id == current_user.id
          %td= link_to "Edit", edit_answer_path(answer.id)
        -else
          %td
= form_for([@question, @question.answers.build], html: {class: "form-inline"}) do |f|
  = f.label  :file
  = f.file_field  :pdf

  = f.label :typed
  = f.check_box :typed
  = f.submit "Add Answer"