config/routes.rb
Prelims::Application.routes.draw do
  get 'password_resets/new'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'questions#index'
  resources :questions do
    resources :sittings
    resources :question_ratings
    collection { post :search, to: 'questions#index' }

    resources :answers do
      resources :answer_ratings
    end
  end
  resources :password_resets
  resources :questiontags
  resources :finished_questions
  resources :answers do
    resources :answer_ratings
  end
  resources :users
  resources :tags
  resources :user_sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'user_sessions#new',         via: 'get'
  match '/signout', to: 'user_sessions#destroy',     via: 'delete'
  match '/help' => 'static#help', via: 'get'
  match '/summary' => 'static#summary', via: 'get'
  match '/teacher' => 'static#teacher', via: 'get'
end

app/models/sitting.rb
# == Schema Information
#
# Table name: sittings
#
#  id          :integer          not null, primary key
#  term_id     :integer
#  year        :integer
#  number      :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  question_id :integer
#

### Sitting Model
class Sitting < ActiveRecord::Base
  belongs_to :term
  belongs_to :question
  validates :number, presence: true
  has_one :subject, through: :question
  def print_sitting
    if term.term == 'Fall'
      "Q#{number}F#{year}"
    else
      "Q#{number}S#{year}"
    end
  end

  def sort_sitting
    if term.term == 'Fall'
      "#{year}F#{number}"
    else
      "#{year}S#{number}"
    end
  end

  def self.table_sittings
    Sitting.joins(:question, :subject, :term)
           .select('number, year, terms.term, subjects.name,
                    question_id, term_id, questions.subject_id')
           .order('subject_id, year DESC, terms.term, number')
  end

  def compare_print
    "#{subject_id}#{year}#{term.term}#{number}"
  end
end

app/controllers/sittings_controller.rb
class SittingsController < ApplicationController
  before_filter :has_question, :only => [:new, :create]
  before_filter :find_sitting_and_question, :only => [:edit, :update]

  protected
  def has_question
    unless (@question = Question.find_by_id(params[:question_id]))
      redirect_to questions_path
    end
  end

  public
  def find_sitting_and_question
    @sitting = Setting.find(params[:id])
    @question = Question.find(params[:id])
  end

  def create
    @question.sittings << @question.sittings.build(sitting_params)
    redirect_to questions_path
  end

  def new
    @sitting = @question.sittings.build
  end

  def edit
  end

  def update
    if @sitting.update_attributes(sitting_params)
       flash[:success] = "Sitting updated"
      redirect_to :root
    else
      render 'edit'
    end
  end
end

private
def sitting_params
  params.require(:sitting).permit!
end

app/views/sittings/_form.html.haml
= form_for [@question, @sitting] do |e|
  .field
    = e.label :year
    = e.select :year, (1990..2013)
  .field
    = e.label  :term
    = e.collection_select :term_id, Term.all, :id, :term, include_blank: true
  .field
    = e.label  :number
    = e.text_field  :number 
  .actions
    = e.submit

app/views/sittings/edit.html.haml
%h1 Edit Sitting

= render 'form'

app/views/sittings/new.html.haml
= form_tag question_sittings_path(@question) do
  .field
    %label Year:
    = select_tag 'sitting[year]', options_for_select(2000..2013)
  .field
    %label  Term:
    = collection_select :sitting, :term_id, Term.all, :id, :term, include_blank: true
  .field
    %label  Number:
    = text_field  :sitting, :number
  %p
    = submit_tag 'Save Sitting'